//
// Created by ivan on 25.3.21.
//

#ifndef RELOAD_MEMALLOCATOR_H
#define RELOAD_MEMALLOCATOR_H

#include "../Common.h"

enum VulkanMemoryUsage {
    VK_MEMORY_USAGE_UNKNOWN,
    VK_MEMORY_USAGE_GPU_ONLY,
    VK_MEMORY_USAGE_CPU_ONLY,
    VK_MEMORY_USAGE_CPU_TO_GPU,
    VK_MEMORY_USAGE_GPU_TO_CPU,
    VK_MEMORY_USAGES,
};

enum VulkanAllocationType {
    VK_ALLOCATION_TYPE_FREE,
    VK_ALLOCATION_TYPE_BUFFER,
    VK_ALLOCATION_TYPE_IMAGE,
    VK_ALLOCATION_TYPE_IMAGE_LINEAR,
    VK_ALLOCATION_TYPE_IMAGE_OPTIMAL,
    VK_ALLOCATION_TYPES,
};

uint32_t FindMemoryTypeIndex(uint32_t memoryTypeBits, VulkanMemoryUsage usage);

#endif //RELOAD_MEMALLOCATOR_H
